### ISSUE TITLE
Assets issue

### ISSUE THREAD

**Issue by tkurki** [SignalK/calibration#1]
![image](https://user-images.githubusercontent.com/1049678/49245515-36791780-f41b-11e8-89c7-286ed4be18f4.png)

**Comment by tkurki** [comment]
![image](https://user-images.githubusercontent.com/1049678/49246127-d2efe980-f41c-11e8-864c-8d67f6d30710.png)

**Comment by Fixh1** [comment]
Hi, I tried to start the calibrations plugin but than got an error:
Could not get calibration configuration:TypeError: topConfig.configuration is undefined
What am I doing wrong?
Regards
Hans

**Comment by Fixh1** [comment]
Sorry, found out what I was doing wrong, I should have con to the plugin config.!

**Comment by tkurki** [comment]
![image](https://user-images.githubusercontent.com/1049678/100268587-ef688300-2f5d-11eb-9b5e-4358af94d110.png)
