### ISSUE TITLE
Correction not applied correctly

### ISSUE THREAD

**Issue by LuckPeerlings** [SignalK/calibration#10]
When applying the calibration, the updated values are sometimes not following the calibration table. 

When applying a negative number, the results are off. 
When using (small) positive numbers, the values are correct. 

**Example**
Excerpt Log File where a calibration between [-0.2,0.1] rad is given (see table in below MWE). Applied differences are in the order of 2 rad.
Nov 02 21:12:56 2024-11-02T20:12:56.980Z @signalk/calibration navigation.courseOverGroundMagnetic(TestFile.II) 3.648610802127232 => 5.5016394631116565)
Nov 02 21:12:57 2024-11-02T20:12:57.387Z @signalk/calibration navigation.courseOverGroundMagnetic(TestFile.II) 3.653672256959171 => 5.5160544645896685)
Nov 02 21:12:57 2024-11-02T20:12:57.794Z @signalk/calibration navigation.courseOverGroundMagnetic(TestFile.II) 3.6514033289310603 => 5.509592567375386) 

**Version**
SignalK server version 2.11.0
Calibration plugin version 1.3.1

**MWE**
1. Create Filestream with the default NMEA 0183 file "/usr/lib/node_modules/signalk-server/samples/plaka.log"
2. Apply calibration
![bild](https://github.com/user-attachments/assets/513d7104-55b8-4d8d-bd53-31cce68d2da5)
3. Changing the calibration values, such that the differences are all positive (0.1rad) resolves the issue.

**Comment by tkurki** [comment]
See #11. If you remove the period your config should work, but the values won't be capped to `[0, Math.PI]`.
