### ISSUE TITLE
how to correct for magnetic variation

### ISSUE THREAD

**Issue by tmcolby** [SignalK/calibration#9]
sorry if this is the wrong place to post this...

i am trying to "calibarate" my magnetic heading to display as true north.  my heading sensor is on my n2k network.  my chartplotter automatically applies the magnetic.variation (in my case 15.6 deg or .2722 rad) to the magnetic heading.

how do i use signalk/calibration to apply a .2722 radian offset to the navigation.headingMagnetic path?

i have tried this 2 point calibration.. but dont see any change to the output
![Screenshot from 2021-08-27 11-39-15](https://user-images.githubusercontent.com/10408450/131174210-c82e8beb-7673-45eb-aacf-b10aefbeddad.png)

**Comment by tkurki** [comment]
Use 2 points outside the practical range of the value, for example input values -10 and 10.

And you found the correct place.

**Comment by tmcolby** [comment]
thanks for the feedback.  just tried this:
![Screenshot from 2021-08-27 12-22-31](https://user-images.githubusercontent.com/10408450/131178750-5c42235d-2514-42d8-958d-269f190911ec.png)

perhaps i have a different issue..  it seems that nothing that i enter in the calibration plugin is having an effect on the value at the specified path. i enabled logging, but dont see any relevant server logs.  any quick an dirty test i can try to prove that calibration plugin is truly manipulating the value?

**Comment by tmcolby** [comment]
ok... specifying a source of `can0.0` might be the missing ingredient here.  digging in a bit more..

**Comment by tmcolby** [comment]
ok.. i got it working.

with cal points that were OUTSIDE the practical range of the value, i got incorrect readings.  doing the same .2722 rad offset on values INDSIDE the practical range (0-6.28318) did the trick.

also, when i had `source` unspecified/blank, the transom was not occurring.  now that i set the source correctly everything is working as it should.  thanks for the help.. and thanks for the contribution.

final (working) settings.
![Screenshot from 2021-08-27 12-34-26](https://user-images.githubusercontent.com/10408450/131179801-c7777406-08e3-49cb-8b75-bed15e93b177.png)
